/**
 * 무드 분류 규칙.
 *
 * 우선순위: SONG_MOOD > ARTIST_MOOD > 장르 규칙 > 'both'
 *
 * 'both'는 "애매하니 드라이브·잔잔 양쪽에 다 넣는다"는 뜻이다.
 * 판단이 서지 않는 곡을 억지로 한쪽에 몰아넣는 것보다 낫다.
 *
 * 이 파일만 고치면 분류가 바뀐다 — `mtym moods` 를 다시 돌리면 된다.
 */
import type { Mood } from '../core/types.js';

/** 신나는 쪽으로 보는 멜론 장르 태그 */
export const DRIVE_GENRES = ['댄스', '랩/힙합', '록/메탈', '일렉트로니카', '게임'];

/** 잔잔한 쪽으로 보는 멜론 장르 태그 */
export const CALM_GENRES = ['발라드', '포크/블루스', '포크', '재즈', '컨트리'];

/** '팝송' 플레이리스트에 넣을 장르 태그 */
export const POP_GENRES = ['POP'];

/** 아티스트 전반의 성향. 곡별 예외는 SONG_MOOD가 덮어쓴다. */
export const ARTIST_MOOD: Record<string, Mood> = {
    SAAY: 'drive',
    'Dua Lipa': 'drive',
    'Bebe Rexha': 'drive',
    Halsey: 'drive',
    'Marian Hill': 'drive',
    Lizzo: 'drive',
    'HUNTR/X': 'drive',
    'KPop Demon Hunters Cast': 'drive',
    Kiiara: 'drive',
    BENEE: 'drive',
    'Mae Muller': 'drive',
    Abir: 'drive',
    'Mia Rodriguez': 'drive',
    'Maggie Lindemann': 'drive',

    'Melanie Martinez': 'calm',
    'Billie Eilish': 'calm',
    'Sam Smith': 'calm',
    'Alec Benjamin': 'calm',
    'Sasha Alex Sloan': 'calm',
    Giveon: 'calm',
    'H.E.R.': 'calm',
    Kehlani: 'calm',
    Gallant: 'calm',
    KATIE: 'calm',
    Seori: 'calm',
    '헤이즈 (Heize)': 'calm',
    '태연 (TAEYEON)': 'calm',
    Jclef: 'calm',
    Meego: 'calm',
    '다비 (DAVII)': 'calm',
    'CHEEZE (치즈)': 'calm',
    'Hoody (후디)': 'calm',
};

/** 곡 단위 판정. 키는 "첫 아티스트|곡명" (대소문자·기호는 비교 시 무시된다) */
export const SONG_MOOD: Record<string, Mood> = {
    // Taylor Swift
    'Taylor Swift|Shake It Off': 'drive',
    'Taylor Swift|Cruel Summer': 'drive',
    'Taylor Swift|Blank Space': 'drive',
    'Taylor Swift|ME! (Feat. Brendon Urie)': 'drive',
    'Taylor Swift|Anti-Hero': 'drive',
    'Taylor Swift|The Fate of Ophelia': 'drive',
    'Taylor Swift|Opalite': 'drive',
    'Taylor Swift|Wood': 'drive',
    'Taylor Swift|Wi$h Li$t': 'drive',
    'Taylor Swift|Wildest Dreams': 'calm',
    'Taylor Swift|Lover': 'calm',
    'Taylor Swift|Delicate': 'calm',
    'Taylor Swift|The Alchemy': 'calm',

    // Billie Eilish (기본 calm)
    'Billie Eilish|bury a friend': 'drive',
    'Billie Eilish|you should see me in a crown': 'drive',
    'Billie Eilish|COPYCAT': 'drive',
    'Billie Eilish|my strange addiction': 'drive',
    'Billie Eilish|all the good girls go to hell': 'drive',
    'Billie Eilish|Therefore I Am': 'drive',
    'Billie Eilish|bellyache': 'drive',
    "Billie Eilish|I Didn't Change My Number": 'drive',
    'Billie Eilish|Happier Than Ever': 'both',
    'Billie Eilish|BIRDS OF A FEATHER': 'both',

    // Melanie Martinez (기본 calm)
    'Melanie Martinez|Pity Party': 'drive',
    'Melanie Martinez|Fire Drill': 'drive',
    'Melanie Martinez|Pacify Her': 'drive',
    "Melanie Martinez|Tag, You're It": 'drive',
    'Melanie Martinez|POSSESSION': 'drive',
    'Melanie Martinez|DEATH': 'drive',
    'Melanie Martinez|EVIL': 'drive',
    'Melanie Martinez|NYMPHOLOGY': 'drive',
    'Melanie Martinez|BATTLE OF THE LARYNX': 'drive',
    'Melanie Martinez|MOON CYCLE': 'drive',
    'Melanie Martinez|Dollhouse': 'drive',

    // Ariana Grande
    'Ariana Grande|7 rings': 'drive',
    'Ariana Grande|Side To Side (Feat. Nicki Minaj)': 'drive',
    "Ariana Grande|break up with your girlfriend, i'm bored": 'drive',
    'Ariana Grande|Love Me Harder': 'drive',
    'Ariana Grande|Popular': 'drive',
    'Ariana Grande|One Last Time': 'drive',
    'Ariana Grande|Best Mistake (Feat. Big Sean)': 'calm',
    'Ariana Grande|Stuck with U': 'calm',
    'Ariana Grande|thank u, next': 'calm',

    // Charlie Puth
    'Charlie Puth|Attention': 'drive',
    'Charlie Puth|How Long': 'drive',
    'Charlie Puth|Done for Me (feat. Kehlani)': 'drive',
    "Charlie Puth|I Don't Think That I Like Her": 'drive',
    'Charlie Puth|One Call Away': 'calm',
    "Charlie Puth|That's Hilarious": 'calm',
    'Charlie Puth|Dangerously': 'calm',

    // Ed Sheeran
    'Ed Sheeran|2step (feat. Lil Baby)': 'drive',
    'Ed Sheeran|Drive': 'drive',
    'Ed Sheeran|Curtains': 'drive',
    'Ed Sheeran|Perfect': 'calm',
    'Ed Sheeran|Happier': 'calm',
    'Ed Sheeran|Supermarket Flowers': 'calm',
    'Ed Sheeran|Boat': 'calm',
    'Ed Sheeran|Eyes Closed': 'calm',

    // 팝 (신나는)
    'Sabrina Carpenter|Espresso': 'drive',
    'Sabrina Carpenter|Taste': 'drive',
    'Sabrina Carpenter|In My Bed': 'drive',
    'Sabrina Carpenter|Please Please Please': 'drive',
    'Olivia Rodrigo|good 4 u': 'drive',
    'Harry Styles|As It Was': 'drive',
    'Harry Styles|Late Night Talking': 'drive',
    'Katy Perry|Never Really Over': 'drive',
    'Sia|Unstoppable': 'drive',
    'Michael Jackson|Smooth Criminal': 'drive',
    "Pharrell Williams|Happy (Gru's Theme From Despicable Me 2)": 'drive',
    'Mark Ronson|Uptown Funk (Feat. Bruno Mars)': 'drive',
    'Britney Spears|Gimme More': 'drive',
    'Bella Poarch|Build a Bitch': 'drive',
    'Zedd|Good Thing': 'drive',
    'Sub Urban|RABBIT HOLE': 'drive',
    'The Kid LAROI|STAY': 'drive',
    'Anne-Marie|2002': 'drive',
    "Destiny's Child|Survivor": 'drive',
    'Doja Cat|Say So': 'drive',
    'Justin Bieber|Ghost': 'drive',
    'Glass Animals|Toes': 'drive',
    'Benson Boone|Beautiful Things': 'drive',
    'Bazzi|Crazy': 'drive',
    'Tayla Parx|Dance Alone': 'drive',
    'Tayla Parx|Rich': 'drive',
    'Charlotte Lawrence|Why Do You Love Me': 'drive',
    "Charlotte Lawrence|Joke's On You": 'drive',
    'Em Beihold|Numb Little Bug': 'drive',
    'bülow|Honor Roll': 'drive',
    'GAYLE|ur just horny': 'drive',
    "EMELINE|cinderella's dead": 'drive',
    'AViVA|EVIL': 'drive',
    'Kailee Morgue|Siren': 'drive',
    'Jax|Ring Pop': 'drive',
    'Chlöe|Treat Me': 'drive',
    'KIDDO|Dead Alive': 'drive',
    'Chymes|Game Over': 'drive',
    'Cat & Calmell|dramatic': 'drive',
    'Ruel|Face To Face': 'drive',
    'Charlotte Cardin|Dirty Dirty': 'drive',
    'Lilianna Wilde|Grind Me Down': 'drive',
    'CHROMANCE|Wrap Me In Plastic (Marcus Layton Radio Edit)': 'drive',
    'Tommee Profitt|In The End (Mellen Gi Remix) (Feat. Fleurie)': 'drive',
    'Stellar|Ashes': 'drive',
    "Raffaella|NASA's Fake": 'drive',
    'tiLLie|Peachie': 'drive',
    'MNEK|Phone': 'drive',
    'Marino|Devil in Disguise': 'drive',
    'George Ezra|Green Green Grass': 'drive',
    'Hailee Steinfeld|End This (L.O.V.E.)': 'drive',
    'Don Toliver|Lose My Mind (feat. Doja Cat)': 'drive',
    'Disney|Zoo (From "Zootopia 2"/Soundtrack Version)': 'drive',
    'Kristen Bell|For The First Time In Forever': 'drive',
    'Straight No Chaser|Text Me Merry Christmas (Feat. Kristen Bell)': 'drive',
    'Ayumu Imazu|Obsessed': 'drive',
    'DPR IAN|Don’t Go Insane': 'drive',

    // 팝 (잔잔)
    'Olivia Rodrigo|drivers license': 'calm',
    'Sia|Snowman': 'calm',
    'Justin Bieber|Off My Face': 'calm',
    'Justin Bieber|Peaches (Feat. Daniel Caesar, Giveon)': 'calm',
    'Justin Bieber|Love Yourself': 'calm',
    'Lady Gaga|Shallow': 'calm',
    'christina perri|a thousand years': 'calm',
    'Lorde|Liability': 'calm',
    'Jeremy Zucker|comethru': 'calm',
    'Selena Gomez|Lose You To Love Me': 'calm',
    'Dean Lewis|Be Alright': 'calm',
    'Jasmine Thompson|Old Friends': 'calm',
    'Kelly Clarkson|Because Of You': 'calm',
    'Ruth B|If By Chance': 'calm',
    'Tate McRae|slower': 'calm',
    'Troye Sivan|Postcard': 'calm',
    'keshi|summer': 'calm',
    'Johnny Stimson|Flower': 'calm',
    'Benson Boone|In The Stars': 'calm',
    'Benson Boone|Ghost Town': 'calm',
    'Katy Perry|Harleys In Hawaii': 'calm',
    'Sabrina Carpenter|Honeymoon Fades': 'calm',
    'Bazzi|Myself': 'calm',
    'Bazzi|Eyes': 'calm',
    'Tayla Parx|Flowers': 'calm',
    'Tayla Parx|Residue': 'calm',
    'Charlotte Lawrence|Slow Motion': 'calm',
    'Em Beihold|Groundhog Day': 'calm',
    'Em Beihold|Too Precious': 'calm',
    'Kiiara|I Still Do': 'calm',
    'Kiiara|Open My Mouth (Stripped)': 'calm',
    'BENEE|Soaked': 'calm',
    'bülow|Sweet Little Lies': 'calm',
    'Maty Noyes|Spiraling Down': 'calm',
    'Maty Noyes|New Friends': 'calm',
    'Lana Del Rey|Born To Die (Album Version)': 'calm',
    "Two Feet|I Feel Like I'm Drowning": 'calm',
    'Ashe|Figured Out': 'calm',
    'John K|parachute': 'calm',
    'Dhruv|double take': 'calm',
    'Mina Okabe|Every Second': 'calm',
    'James Smith|Tell Me That You Love Me': 'calm',
    'AJ Mitchell|Like Strangers Do': 'calm',
    "Chloe Lilac|Here's Your Song": 'calm',
    'Finn Askew|Roses': 'calm',
    'ZAYN|Rainberry': 'calm',
    'Alex Warren|On My Mind': 'calm',
    'Fin Argus|Clouds': 'calm',
    "LAUV|i'm so tired...": 'calm',
    'Lauren Jauregui|Expectations': 'calm',
    'Kiana Lede|EX': 'calm',
    'Jeremy Passion|All Smiles': 'calm',
    'Nina Cobham|interested': 'calm',
    'Jeff Bernat|Make Up Your Mind': 'calm',
    'J.Tajor|Like I Do': 'calm',
    'Doja Cat|Like That (feat. Gucci Mane)': 'calm',
    'Doja Cat|You Right': 'calm',

    // Alessia Cara
    'Alessia Cara|Growing Pains': 'drive',
    'Alessia Cara|Trust My Lonely': 'drive',
    'Alessia Cara|Not Today': 'drive',
    'Alessia Cara|Rooting For You': 'drive',
    'Alessia Cara|How Far I\'ll Go (From "Moana"/Alessia Cara Version)': 'drive',
    'Alessia Cara|Here': 'calm',
    'Alessia Cara|Scars To Your Beautiful': 'calm',
    'Alessia Cara|Out Of Love': 'calm',
    'Alessia Cara|Stone (Feat. Sebastian Kole)': 'calm',
    'Alessia Cara|River Of Tears': 'calm',
    'Alessia Cara|You Let Me Down': 'calm',
    'Alessia Cara|Make It To Christmas': 'calm',
    'Alessia Cara|I Choose (From The Netflix Original Film The Willoughbys)': 'calm',
    'Alessia Cara|Sweet Dream': 'calm',
    "Alessia Cara|I Miss You, Don't Call Me": 'calm',
    'Alessia Cara|The Use In Trying': 'calm',

    // J-POP / 애니
    'aimyon|Kimi Wa Rock Wo Kikanai': 'drive',
    'aimyon|Ai Wo Tsutaetaidatoka': 'drive',
    'aimyon|Naked Heart': 'calm',
    'Kenshi Yonezu|IRIS OUT': 'drive',
    'Kenshi Yonezu|打上花火 / Uchiagehanabi (쏘아올린 불꽃)': 'calm',
    'YOASOBI|夜に駆ける (밤을 달리다, Into The Night / Yoru ni Kakeru)': 'drive',
    'Ado|Backlight (UTA from ONE PIECE FILM RED)': 'drive',

    // 한국 (신나는)
    '비비 (BIBI)|사랑의 묘약': 'drive',
    '비비 (BIBI)|가면무도회': 'drive',
    '비비 (BIBI)|모토스피드 24시': 'drive',
    '비비 (BIBI)|철학보다 무서운건 비비의 총알': 'drive',
    '비비 (BIBI)|조또': 'drive',
    '비비 (BIBI)|Amigos (Explicit Ver.)': 'drive',
    '헤이즈 (Heize)|Dispatch (Feat. Simon Dominic)': 'drive',
    "Seori|Can't Stop This Party": 'drive',
    'Seori|Trigger': 'drive',
    '로제 (ROSÉ)|dance all night': 'drive',
    '로제 (ROSÉ)|gameboy': 'drive',
    '로제 (ROSÉ)|Messy': 'drive',
    'aespa|Hot Mess': 'drive',
    'NewJeans|Supernatural': 'drive',
    '류수정|T-Shirt': 'drive',
    '류수정|Love or Hate': 'drive',
    '그루비룸 (GroovyRoom)|Yes or No (Feat. 허윤진 of LE SSERAFIM, Crush)': 'drive',
    'JAMIE (제이미)|Numbers (Feat. 창모 (CHANGMO))': 'drive',
    'JAMIE (제이미)|Apollo 11 (Feat. 박재범)': 'drive',
    '백다연|DRIVE ME (이 밤을 내게줘)': 'drive',
    'Lolo Zouai (롤로 주아이)|Caffeine': 'drive',
    'Lolo Zouai (롤로 주아이)|Money Diamonds Roses': 'drive',
    'Lolo Zouai (롤로 주아이)|pl4yg1rl': 'drive',

    // 한국 (잔잔)
    '비비 (BIBI)|밤양갱': 'calm',
    '비비 (BIBI)|나비': 'calm',
    '비비 (BIBI)|자국': 'calm',
    '비비 (BIBI)|종말의 사과나무': 'calm',
    '로제 (ROSÉ)|too bad for us': 'calm',
    '로제 (ROSÉ)|drinks or coffee': 'calm',
    'aespa|Flowers': 'calm',
    'IVE (아이브)|Either Way': 'calm',
    'The Weeknd|Die For You': 'calm',
    'Lolo Zouai (롤로 주아이)|High Highs to Low Lows': 'calm',
    'Lolo Zouai (롤로 주아이)|Brooklyn Love': 'calm',
    'Lolo Zouai (롤로 주아이)|Moi': 'calm',
    '죠지|Boat': 'calm',
    '이하이|구원자 (Feat. B.I)': 'calm',
    '브라운아이드걸스|다가와서': 'calm',
    'HYNN (박혜원)|To You (Prod. 정키)': 'calm',
    '마크툽 (MAKTUB)|시작의 아이': 'calm',
    '박다혜|시작의 아이 ❍': 'calm',
    '박화요비|그런 일은': 'calm',
    '015B|L': 'calm',
    '니브 (NIve)|2easy(ft.헤이즈)': 'calm',
    '프라이머리|When I fall in love (Feat. Meego, 수란)': 'calm',
    '코드 쿤스트 (CODE KUNST)|XI (Feat. 이하이)': 'calm',
    '원슈타인|중고인간 (Feat. Jclef)': 'calm',
    'WSG워너비(4FIRE)|보고싶었어': 'calm',
    '유성은|마리화나': 'calm',
    '던 (DAWN)|빛이 나는 너에게': 'calm',
    '박재범|Yesterday': 'calm',
    'SOLE (쏠)|머물러 있는 것 또한 아름다울 수 있는 건': 'calm',
    '다레|Moon On The Ocean (Feat. 김승민)': 'calm',
    'JAMIE (제이미)|Stay Beautiful': 'calm',
    'i-dle (아이들)|Change': 'calm',

    // SAAY 예외 (기본 drive)
    'SAAY|QUIET DOWN': 'calm',
    'SAAY|Summer In Love (Feat. Colde)': 'calm',
    'SAAY|STAY': 'calm',
    "SAAY|I'M OKAY": 'calm',
};
